remote_theme: daviddarnes/alembic

navigation_header:
  Home: /
  Project 1: /project1/project_1.html
  Project 2: /project2/project2.html
  Project 3: /bloededam/bloededameproject.html  
  Project 4: /finalproject/finalproject.html
  Project 5: /soilerosion/soilerosion.html
  Contact: /contact/contact.html
  
