remote_theme: daviddarnes/alembic

navigation_header:
  Home: /
  Baltimore Industries: /project1/project_1.html
  Coral Beaching: /project2/project2.html
  Final Project Proposal: /final_proposal.html
  Bloede Dam Project: /bloededam/bloededameproject.html
  
