remote_theme: daviddarnes/alembic

navigation_header:
  Home: /
  Project 1: /project1/project_1.html
  Project 2: /project2/project2.html
  Project 3: /finalproject/finalproject.html
  Project 4: /bloededam/bloededameproject.html
  Project 5: /soilerosion/soilerosion.html
  
